services:
  db:
    image: postgres:16
    container_name: mugi_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: mugi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: